#!/usr/bin/env bash


activate-conda(){
    if [ -z "${ADNOC_PATH}" ]
    then
        export ADNOC_PATH="/usr/local/miniconda3/bin"
        export ORIGINAL_PATH="${PATH}"
        export PATH="${ADNOC_PATH}:${PATH}"
	echo "Conda has been activated"
    else
        echo "Conda already activated"
    fi
}

deactivate-conda(){
    if [ ! -z "${ADNOC_PATH}" ]
    then
        export ADNOC_PATH=""
        export PATH="${ORIGINAL_PATH}"
        export ORIGINAL_PATH=""
        echo "Conda has been deactivated"
    else
        echo "Conda is not active"
    fi
}

ar(){
    activate-conda
    if [ -z ${ADNOC_PATH} ]
    then
        echo "Can't activate research environment"
    else
        source activate research
	export PS1="╭ \033[01;33m\]\u\033[01;31m\]♖ \033[01;32m\]\h\033[00m\]:\033[01;34m\]\w\033[01;35m\]$(__git_ps1 " (%s)")\033[00m\] (research)\n╰> "
    fi
}

dr(){
    source deactivate
    if [ $? -eq 0 ]
    then
        deactivate-conda
    else
        echo "No research environment to deactivate"
    fi
}

go() {
    if [ -f "$1" ]; then
        if [ -n "`file $1 | grep '\(text\|empty\|no magic\)'`" ]; then
            if [ -w "$1" ]; then
                $EDITOR "$1"
            else
                sudo $EDITOR "$1"
                #$EDITOR /sudo::"$1" # For emacsclient+tramp
            fi
        else
            if [ -e "`which xdg-open`" ]; then
                if [ -n "$DISPLAY" ]; then
                    xdg-open "$1" > /dev/null
                else
                    echo "DISPLAY not set:  xdg-open requires X11"
                fi
            else
                echo "xdg-open not found:  unable to open '$1'"
            fi
        fi
    elif [ -d "$1" ]; then
        cd "$1"
    elif [ "" = "$1" ]; then
        cd
    elif [ -n "`declare -f | grep '^j ()'`" ]; then
        j "$1"
    else
        echo "Ran out of things to do with '$1'"
    fi
}
