#!/usr/bin/env bash

#SSH Aliases
alias ssh-hal="ssh autorefactorer.com"
alias ssh-wedding="ssh alisonmichaelwedding.com"
alias ssh-diannao="ssh DianNao"

alias spacemacs="emacs"
alias space="emacs"

alias jn="jupyter-notebook"

#Fasd aliases
eval "$(fasd --init auto)"

#Alias for my go command for added laziness
alias g=go

#Alias for restart-chunk command for added laziness
alias rc=restart-chunk
