#!/usr/bin/env bash


activate-conda(){
    if [ -z "${CONDA_PATH}" ]
    then
        export ADNOC_PATH="/usr/local/miniconda3/bin"
        export ORIGINAL_PATH="${PATH}"
        export PATH="${ADNOC_PATH}:${PATH}"
	echo "Conda has been activated"
    else
        echo "Conda already activated"
    fi
}

deactivate-conda(){
    if [ ! -z "${ADNOC_PATH}" ]
    then
        export ADNOC_PATH=""
        export PATH="${ORIGINAL_PATH}"
        export ORIGINAL_PATH=""
        echo "Conda has been deactivated"
    else
        echo "Conda is not active"
    fi
}
