#!/usr/bin/env bash

#SSH Aliases
alias ssh-hal="ssh autorefactorer.com"
alias ssh-wedding="ssh alisonmichaelwedding.com"
alias ssh-diannao="ssh DianNao"

alias spacemacs="emacs"

alias jn="jupyter-notebook"

#Fasd aliases
eval "$(fasd --init auto)"

alias g=go
