#!/usr/bin/env bash

#Settings for colored text within bash
#Desired outcome: PS1='╭ \033[01;33m\]\u\033[01;31m\]♖ \033[01;32m\]\h\033[00m\]:\033[01;34m\]\w\033[01;35m\]$(__git_ps1 " (%s)")\033[00m\]\n╰> '
PS1='╭ \[\033[01;31m\]\t \[\033[01;32m\]\u 🍦  \[\033[01;33m\]\h: \[\033[01;36m\]\w' 
if [ -f "/opt/local/share/git/git-prompt.sh" ]
then
    source "/opt/local/share/git/git-prompt.sh"	
    PS1=${PS1}'\033[01;35m\]$(__git_ps1 " (%s)")' 
fi
export PS1=${PS1}'\[\033[00m\]\n╰> '
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

