#!/usr/bin/env bash


activate-conda(){
    if [ -z "${ADNOC_PATH}" ]
    then
        export ADNOC_PATH="/usr/local/miniconda3/bin"
        export ORIGINAL_PATH="${PATH}"
        export PATH="${ADNOC_PATH}:${PATH}"
	echo "Conda has been activated"
    else
        echo "Conda already activated"
    fi
}

deactivate-conda(){
    if [ ! -z "${ADNOC_PATH}" ]
    then
        export ADNOC_PATH=""
        export PATH="${ORIGINAL_PATH}"
        export ORIGINAL_PATH=""
        echo "Conda has been deactivated"
    else
        echo "Conda is not active"
    fi
}

ar(){
    activate-conda
    if [ -z ${ADNOC_PATH} ]
    then
        echo "Can't activate research environment"
    else
        source activate research
	export PS1="╭ \033[01;33m\]\u\033[01;31m\]♖ \033[01;32m\]\h\033[00m\]:\033[01;34m\]\w\033[01;35m\]$(__git_ps1 " (%s)")\033[00m\] (research)\n╰> "
    fi
}

dr(){
    source deactivate
    if [ $? -eq 0 ]
    then
        deactivate-conda
    else
        echo "No research environment to deactivate"
    fi
}
