#!/usr/bin/env bash

#Setup for using tmux immediately at interactive login
#Will attach to any existing tmux session at login,
#and re-attach to any existing tmux, should others exist, at logout,
#until there are none remaining
#[[ $- != *i* ]] && return
#if which tmux >/dev/null 2>&1 && [ -z "${TMUX}" ]
#then
#       tmux attach || tmux new-session
#       while [ -z ${TMUX} ]
#               do
#               tmux attach || break
#       done
#fi

