#!/usr/bin/env bash

#Settings for colored text within bash
export PS1="╭ \033[01;33m\]\u\033[01;31m\]♖ \033[01;32m\]\h\033[00m\]:\033[01;34m\]\w\033[00m\]\n╰> "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

